  public void testThrowRuntimeException() throws Throwable {
    debug.logStart();
    _log.log("NewJVMTest.testThrowRuntimeException executing");
    
    _jvm.resetFlags();
    assertTrue(_jvm.interpret("throw new RuntimeException();"));
    assertTrue("exception message", _jvm.exceptionMsgBuf().startsWith("java.lang.RuntimeException"));

    debug.logEnd();
  }
