  public void testOpenNonexistentFile() throws IOException {
    _model.addListener(new TestListener());
    
    OpenDefinitionsDocument doc = null;
    
    try {
      doc = _model.openFile(new FileSelector(new File("fake-file")));
      fail("IO exception was not thrown!");
    }
    catch (FileNotFoundException fnf) {
    }
    catch (AlreadyOpenException aoe) {
      fail("File was already open!");
    }
    catch (OperationCanceledException oce) {
      fail("Open was unexpectedly canceled!");
    }
    
    assertEquals("non-existant file", doc, null);
    
    _log.log("testOpenNonexistentFile completed");
  }
